package utils

import "errors"

var ErrorLanguageNotFound = errors.New("language not found")

// Language is an ISO 639-1 language with code, name and native name.
type Language struct {
	Code        string
	Name        string
	NativeName  string
	PersianName string
}

// Languages is a map of all ISO 639-1 languages using the two character lowercase language code as key.
var Languages = map[string]Language{
	"aa": {Code: "aa", Name: "Afar", NativeName: "Afaraf", PersianName: "آفار"},
	"ab": {Code: "ab", Name: "Abkhaz", NativeName: "Аҧсуа бызшәа", PersianName: "آبخاز"},
	"ae": {Code: "ae", Name: "Avestan", NativeName: "Avesta", PersianName: "اوستایی"},
	"af": {Code: "af", Name: "Afrikaans", NativeName: "Afrikaans", PersianName: "آفریکانس"},
	"ak": {Code: "ak", Name: "Akan", NativeName: "Akan", PersianName: "آکان"},
	"am": {Code: "am", Name: "Amharic", NativeName: "አማርኛ", PersianName: "امهری"},
	"an": {Code: "an", Name: "Aragonese", NativeName: "Aragonés", PersianName: "آراگونی"},
	"ar": {Code: "ar", Name: "Arabic", NativeName: "اللغة العربية", PersianName: "عربی"},
	"as": {Code: "as", Name: "Assamese", NativeName: "অসমীয়া", PersianName: "آسامی"},
	"av": {Code: "av", Name: "Avaric", NativeName: "Авар мацӀ", PersianName: "آواری"},
	"ay": {Code: "ay", Name: "Aymara", NativeName: "Aymar aru", PersianName: "ایمارا"},
	"az": {Code: "az", Name: "Azerbaijani", NativeName: "Azərbaycan dili", PersianName: "آذربایجانی"},
	"ba": {Code: "ba", Name: "Bashkir", NativeName: "Башҡорт теле", PersianName: "باشقیری"},
	"be": {Code: "be", Name: "Belarusian", NativeName: "Беларуская мова", PersianName: "بلاروسی"},
	"bg": {Code: "bg", Name: "Bulgarian", NativeName: "Български език", PersianName: "بلغاری"},
	"bh": {Code: "bh", Name: "Bihari", NativeName: "भोजपुरी", PersianName: "بیهاری"},
	"bi": {Code: "bi", Name: "Bislama", NativeName: "Bislama", PersianName: "بیسلاما"},
	"bm": {Code: "bm", Name: "Bambara", NativeName: "Bamanankan", PersianName: "بامبارا"},
	"bn": {Code: "bn", Name: "Bengali", NativeName: "বাংলা", PersianName: "بنگالی"},
	"bo": {Code: "bo", Name: "Tibetan Standard", NativeName: "བོད་ཡིག", PersianName: "تبتی"},
	"br": {Code: "br", Name: "Breton", NativeName: "Brezhoneg", PersianName: "برتون"},
	"bs": {Code: "bs", Name: "Bosnian", NativeName: "Bosanski jezik", PersianName: "بوسنیایی"},
	"ca": {Code: "ca", Name: "Catalan", NativeName: "Català", PersianName: "کاتالان"},
	"ce": {Code: "ce", Name: "Chechen", NativeName: "Нохчийн мотт", PersianName: "چچنی"},
	"ch": {Code: "ch", Name: "Chamorro", NativeName: "Chamoru", PersianName: "چامورو"},
	"co": {Code: "co", Name: "Corsican", NativeName: "Corsu", PersianName: "کرسی"},
	"cr": {Code: "cr", Name: "Cree", NativeName: "ᓀᐦᐃᔭᐍᐏᐣ", PersianName: "کری"},
	"cs": {Code: "cs", Name: "Czech", NativeName: "Čeština", PersianName: "چکی"},
	"cu": {Code: "cu", Name: "Old Church Slavonic", NativeName: "Ѩзыкъ словѣньскъ", PersianName: "اسلاوی کلیسایی"},
	"cv": {Code: "cv", Name: "Chuvash", NativeName: "Чӑваш чӗлхи", PersianName: "چوواش"},
	"cy": {Code: "cy", Name: "Welsh", NativeName: "Cymraeg", PersianName: "ولزی"},
	"da": {Code: "da", Name: "Danish", NativeName: "Dansk", PersianName: "دانمارکی"},
	"de": {Code: "de", Name: "German", NativeName: "Deutsch", PersianName: "آلمانی"},
	"dv": {Code: "dv", Name: "Divehi", NativeName: "Dhivehi", PersianName: "دیوهی"},
	"dz": {Code: "dz", Name: "Dzongkha", NativeName: "རྫོང་ཁ", PersianName: "دزونگخا"},
	"ee": {Code: "ee", Name: "Ewe", NativeName: "Eʋegbe", PersianName: "اوه"},
	"el": {Code: "el", Name: "Greek", NativeName: "Ελληνικά", PersianName: "یونانی"},
	"en": {Code: "en", Name: "English", NativeName: "English", PersianName: "انگلیسی"},
	"eo": {Code: "eo", Name: "Esperanto", NativeName: "Esperanto", PersianName: "اسپرانتو"},
	"es": {Code: "es", Name: "Spanish", NativeName: "Español", PersianName: "اسپانیایی"},
	"et": {Code: "et", Name: "Estonian", NativeName: "Eesti", PersianName: "استونیایی"},
	"eu": {Code: "eu", Name: "Basque", NativeName: "Euskara", PersianName: "باسکی"},
	"fa": {Code: "fa", Name: "Persian", NativeName: "فارسی", PersianName: "فارسی"},
	"ff": {Code: "ff", Name: "Fula", NativeName: "Fulfulde", PersianName: "فولانی"},
	"fi": {Code: "fi", Name: "Finnish", NativeName: "Suomi", PersianName: "فنلاندی"},
	"fj": {Code: "fj", Name: "Fijian", NativeName: "Vakaviti", PersianName: "فیجی"},
	"fo": {Code: "fo", Name: "Faroese", NativeName: "Føroyskt", PersianName: "فارویی"},
	"fr": {Code: "fr", Name: "French", NativeName: "Français", PersianName: "فرانسوی"},
	"fy": {Code: "fy", Name: "Western Frisian", NativeName: "Frysk", PersianName: "فریزی غربی"},
	"ga": {Code: "ga", Name: "Irish", NativeName: "Gaeilge", PersianName: "ایرلندی"},
	"gd": {Code: "gd", Name: "Scottish Gaelic", NativeName: "Gàidhlig", PersianName: "گالیک اسکاتلندی"},
	"gl": {Code: "gl", Name: "Galician", NativeName: "Galego", PersianName: "گالیسیایی"},
	"gn": {Code: "gn", Name: "Guaraní", NativeName: "Avañeẽ", PersianName: "گوارانی"},
	"gu": {Code: "gu", Name: "Gujarati", NativeName: "ગુજરાતી", PersianName: "گجراتی"},
	"gv": {Code: "gv", Name: "Manx", NativeName: "Gaelg", PersianName: "منکس"},
	"ha": {Code: "ha", Name: "Hausa", NativeName: "هَوُسَ", PersianName: "هوسا"},
	"he": {Code: "he", Name: "Hebrew", NativeName: "עברית", PersianName: "عبری"},
	"hi": {Code: "hi", Name: "Hindi", NativeName: "हिन्दी", PersianName: "هندی"},
	"ho": {Code: "ho", Name: "Hiri Motu", NativeName: "Hiri Motu", PersianName: "هیری موتو"},
	"hr": {Code: "hr", Name: "Croatian", NativeName: "Hrvatski jezik", PersianName: "کرواتی"},
	"ht": {Code: "ht", Name: "Haitian", NativeName: "Kreyòl ayisyen", PersianName: "هائیتیایی"},
	"hu": {Code: "hu", Name: "Hungarian", NativeName: "Magyar", PersianName: "مجاری"},
	"hy": {Code: "hy", Name: "Armenian", NativeName: "Հայերեն", PersianName: "ارمنی"},
	"hz": {Code: "hz", Name: "Herero", NativeName: "Otjiherero", PersianName: "هررو"},
	"ia": {Code: "ia", Name: "Interlingua", NativeName: "Interlingua", PersianName: "اینترلینگوا"},
	"id": {Code: "id", Name: "Indonesian", NativeName: "Indonesian", PersianName: "اندونزیایی"},
	"ie": {Code: "ie", Name: "Interlingue", NativeName: "Interlingue", PersianName: "اینترلینگو"},
	"ig": {Code: "ig", Name: "Igbo", NativeName: "Asụsụ Igbo", PersianName: "ایگبو"},
	"ii": {Code: "ii", Name: "Nuosu", NativeName: "ꆈꌠ꒿ Nuosuhxop", PersianName: "نوسو"},
	"ik": {Code: "ik", Name: "Inupiaq", NativeName: "Iñupiaq", PersianName: "اینوپیاک"},
	"io": {Code: "io", Name: "Ido", NativeName: "Ido", PersianName: "ایدو"},
	"is": {Code: "is", Name: "Icelandic", NativeName: "Íslenska", PersianName: "ایسلندی"},
	"it": {Code: "it", Name: "Italian", NativeName: "Italiano", PersianName: "ایتالیایی"},
	"iu": {Code: "iu", Name: "Inuktitut", NativeName: "ᐃᓄᒃᑎᑐᑦ", PersianName: "اینوکتیتوت"},
	"ja": {Code: "ja", Name: "Japanese", NativeName: "日本語", PersianName: "ژاپنی"},
	"jv": {Code: "jv", Name: "Javanese", NativeName: "Basa Jawa", PersianName: "جاوه‌ای"},
	"ka": {Code: "ka", Name: "Georgian", NativeName: "Ქართული", PersianName: "گرجی"},
	"kg": {Code: "kg", Name: "Kongo", NativeName: "Kikongo", PersianName: "کنگویی"},
	"ki": {Code: "ki", Name: "Kikuyu", NativeName: "Gĩkũyũ", PersianName: "کیکویو"},
	"kj": {Code: "kj", Name: "Kwanyama", NativeName: "Kuanyama", PersianName: "کوانیاما"},
	"kk": {Code: "kk", Name: "Kazakh", NativeName: "Қазақ тілі", PersianName: "قزاقی"},
	"kl": {Code: "kl", Name: "Kalaallisut", NativeName: "Kalaallisut", PersianName: "گرینلندی"},
	"km": {Code: "km", Name: "Khmer", NativeName: "ខេមរភាសា", PersianName: "خمری"},
	"kn": {Code: "kn", Name: "Kannada", NativeName: "ಕನ್ನಡ", PersianName: "کانادا"},
	"ko": {Code: "ko", Name: "Korean", NativeName: "한국어", PersianName: "کره‌ای"},
	"kr": {Code: "kr", Name: "Kanuri", NativeName: "Kanuri", PersianName: "کانوری"},
	"ks": {Code: "ks", Name: "Kashmiri", NativeName: "कश्मीरी", PersianName: "کشمیری"},
	"ku": {Code: "ku", Name: "Kurdish", NativeName: "Kurdî", PersianName: "کردی"},
	"kv": {Code: "kv", Name: "Komi", NativeName: "Коми кыв", PersianName: "کومی"},
	"kw": {Code: "kw", Name: "Cornish", NativeName: "Kernewek", PersianName: "کورنیش"},
	"ky": {Code: "ky", Name: "Kyrgyz", NativeName: "Кыргызча", PersianName: "قرقیزی"},
	"la": {Code: "la", Name: "Latin", NativeName: "Latine", PersianName: "لاتین"},
	"lb": {Code: "lb", Name: "Luxembourgish", NativeName: "Lëtzebuergesch", PersianName: "لوکزامبورگی"},
	"lg": {Code: "lg", Name: "Ganda", NativeName: "Luganda", PersianName: "گاندا"},
	"li": {Code: "li", Name: "Limburgish", NativeName: "Limburgs", PersianName: "لیمبورگی"},
	"ln": {Code: "ln", Name: "Lingala", NativeName: "Lingála", PersianName: "لینگالا"},
	"lo": {Code: "lo", Name: "Lao", NativeName: "ພາສາ", PersianName: "لائوسی"},
	"lt": {Code: "lt", Name: "Lithuanian", NativeName: "Lietuvių kalba", PersianName: "لیتوانیایی"},
	"lu": {Code: "lu", Name: "Luba-Katanga", NativeName: "Tshiluba", PersianName: "لوبا کاتانگا"},
	"lv": {Code: "lv", Name: "Latvian", NativeName: "Latviešu valoda", PersianName: "لتونیایی"},
	"mg": {Code: "mg", Name: "Malagasy", NativeName: "Fiteny malagasy", PersianName: "مالاگاسی"},
	"mh": {Code: "mh", Name: "Marshallese", NativeName: "Kajin M̧ajeļ", PersianName: "مارشالی"},
	"mi": {Code: "mi", Name: "Māori", NativeName: "Te reo Māori", PersianName: "مائوری"},
	"mk": {Code: "mk", Name: "Macedonian", NativeName: "Македонски јазик", PersianName: "مقدونی"},
	"ml": {Code: "ml", Name: "Malayalam", NativeName: "മലയാളം", PersianName: "مالایالامی"},
	"mn": {Code: "mn", Name: "Mongolian", NativeName: "Монгол хэл", PersianName: "مغولی"},
	"mr": {Code: "mr", Name: "Marathi", NativeName: "मराठी", PersianName: "مراتی"},
	"ms": {Code: "ms", Name: "Malay", NativeName: "هاس ملايو", PersianName: "مالایی"},
	"mt": {Code: "mt", Name: "Maltese", NativeName: "Malti", PersianName: "مالتی"},
	"my": {Code: "my", Name: "Burmese", NativeName: "ဗမာစာ", PersianName: "برمه‌ای"},
	"na": {Code: "na", Name: "Nauru", NativeName: "Ekakairũ Naoero", PersianName: "نائورو"},
	"nb": {Code: "nb", Name: "Norwegian Bokmål", NativeName: "Norsk bokmål", PersianName: "نروژی بوکمال"},
	"nd": {Code: "nd", Name: "Northern Ndebele", NativeName: "IsiNdebele", PersianName: "ندبله شمالی"},
	"ne": {Code: "ne", Name: "Nepali", NativeName: "नेपाली", PersianName: "نپالی"},
	"ng": {Code: "ng", Name: "Ndonga", NativeName: "Owambo", PersianName: "ندونگا"},
	"nl": {Code: "nl", Name: "Dutch", NativeName: "Nederlands", PersianName: "هلندی"},
	"nn": {Code: "nn", Name: "Norwegian Nynorsk", NativeName: "Norsk nynorsk", PersianName: "نروژی نینورسک"},
	"no": {Code: "no", Name: "Norwegian", NativeName: "Norsk", PersianName: "نروژی"},
	"nr": {Code: "nr", Name: "Southern Ndebele", NativeName: "IsiNdebele", PersianName: "ندبله جنوبی"},
	"nv": {Code: "nv", Name: "Navajo", NativeName: "Diné bizaad", PersianName: "ناواجو"},
	"ny": {Code: "ny", Name: "Chichewa", NativeName: "ChiCheŵa", PersianName: "چیچوا"},
	"oc": {Code: "oc", Name: "Occitan", NativeName: "Occitan", PersianName: "اکسیتان"},
	"oj": {Code: "oj", Name: "Ojibwe", NativeName: "ᐊᓂᔑᓈᐯᒧᐎᓐ", PersianName: "اوجیبوا"},
	"om": {Code: "om", Name: "Oromo", NativeName: "Afaan Oromoo", PersianName: "اورومو"},
	"or": {Code: "or", Name: "Oriya", NativeName: "ଓଡ଼ିଆ", PersianName: "اوریا"},
	"os": {Code: "os", Name: "Ossetian", NativeName: "Ирон æвзаг", PersianName: "آسی"},
	"pa": {Code: "pa", Name: "Panjabi", NativeName: "ਪੰਜਾਬੀ", PersianName: "پنجابی"},
	"pi": {Code: "pi", Name: "Pāli", NativeName: "पाऴि", PersianName: "پالی"},
	"pl": {Code: "pl", Name: "Polish", NativeName: "Język polski", PersianName: "لهستانی"},
	"ps": {Code: "ps", Name: "Pashto", NativeName: "پښتو", PersianName: "پشتو"},
	"pt": {Code: "pt", Name: "Portuguese", NativeName: "Português", PersianName: "پرتغالی"},
	"qu": {Code: "qu", Name: "Quechua", NativeName: "Runa Simi", PersianName: "کچوا"},
	"rm": {Code: "rm", Name: "Romansh", NativeName: "Rumantsch grischun", PersianName: "رومانش"},
	"rn": {Code: "rn", Name: "Kirundi", NativeName: "Ikirundi", PersianName: "کیروندی"},
	"ro": {Code: "ro", Name: "Romanian", NativeName: "Română", PersianName: "رومانیایی"},
	"ru": {Code: "ru", Name: "Russian", NativeName: "Русский", PersianName: "روسی"},
	"rw": {Code: "rw", Name: "Kinyarwanda", NativeName: "Ikinyarwanda", PersianName: "کینیارواندا"},
	"sa": {Code: "sa", Name: "Sanskrit", NativeName: "संस्कृतम्", PersianName: "سانسکریت"},
	"sc": {Code: "sc", Name: "Sardinian", NativeName: "Sardu", PersianName: "ساردینی"},
	"sd": {Code: "sd", Name: "Sindhi", NativeName: "सिन्धी", PersianName: "سندی"},
	"se": {Code: "se", Name: "Northern Sami", NativeName: "Davvisámegiella", PersianName: "سامی شمالی"},
	"sg": {Code: "sg", Name: "Sango", NativeName: "Yângâ tî sängö", PersianName: "سانگو"},
	"si": {Code: "si", Name: "Sinhala", NativeName: "සිංහල", PersianName: "سینهالی"},
	"sk": {Code: "sk", Name: "Slovak", NativeName: "Slovenčina", PersianName: "اسلواکی"},
	"sl": {Code: "sl", Name: "Slovene", NativeName: "Slovenski jezik", PersianName: "اسلوونیایی"},
	"sm": {Code: "sm", Name: "Samoan", NativeName: "Gagana faa Samoa", PersianName: "ساموآیی"},
	"sn": {Code: "sn", Name: "Shona", NativeName: "ChiShona", PersianName: "شونا"},
	"so": {Code: "so", Name: "Somali", NativeName: "Soomaaliga", PersianName: "سومالیایی"},
	"sq": {Code: "sq", Name: "Albanian", NativeName: "Shqip", PersianName: "آلبانیایی"},
	"sr": {Code: "sr", Name: "Serbian", NativeName: "Српски језик", PersianName: "صربی"},
	"ss": {Code: "ss", Name: "Swati", NativeName: "SiSwati", PersianName: "سواتی"},
	"st": {Code: "st", Name: "Southern Sotho", NativeName: "Sesotho", PersianName: "سوتوی جنوبی"},
	"su": {Code: "su", Name: "Sundanese", NativeName: "Basa Sunda", PersianName: "سوندانی"},
	"sv": {Code: "sv", Name: "Swedish", NativeName: "Svenska", PersianName: "سوئدی"},
	"sw": {Code: "sw", Name: "Swahili", NativeName: "Kiswahili", PersianName: "سواحلی"},
	"ta": {Code: "ta", Name: "Tamil", NativeName: "தமிழ்", PersianName: "تامیل"},
	"te": {Code: "te", Name: "Telugu", NativeName: "తెలుగు", PersianName: "تلوگو"},
	"tg": {Code: "tg", Name: "Tajik", NativeName: "Тоҷикӣ", PersianName: "تاجیکی"},
	"th": {Code: "th", Name: "Thai", NativeName: "ไทย", PersianName: "تایلندی"},
	"ti": {Code: "ti", Name: "Tigrinya", NativeName: "ትግርኛ", PersianName: "تیگرینیا"},
	"tk": {Code: "tk", Name: "Turkmen", NativeName: "Türkmen", PersianName: "ترکمنی"},
	"tl": {Code: "tl", Name: "Tagalog", NativeName: "Wikang Tagalog", PersianName: "تاگالوگ"},
	"tn": {Code: "tn", Name: "Tswana", NativeName: "Setswana", PersianName: "تسوانا"},
	"to": {Code: "to", Name: "Tonga", NativeName: "Faka Tonga", PersianName: "تونگا"},
	"tr": {Code: "tr", Name: "Turkish", NativeName: "Türkçe", PersianName: "ترکی"},
	"ts": {Code: "ts", Name: "Tsonga", NativeName: "Xitsonga", PersianName: "تسونگا"},
	"tt": {Code: "tt", Name: "Tatar", NativeName: "Татар теле", PersianName: "تاتاری"},
	"tw": {Code: "tw", Name: "Twi", NativeName: "Twi", PersianName: "توی"},
	"ty": {Code: "ty", Name: "Tahitian", NativeName: "Reo Tahiti", PersianName: "تاهیتی"},
	"ug": {Code: "ug", Name: "Uyghur", NativeName: "ئۇيغۇرچە", PersianName: "اویغوری"},
	"uk": {Code: "uk", Name: "Ukrainian", NativeName: "Українська", PersianName: "اوکراینی"},
	"ur": {Code: "ur", Name: "Urdu", NativeName: "اردو", PersianName: "اردو"},
	"uz": {Code: "uz", Name: "Uzbek", NativeName: "Ўзбек", PersianName: "ازبکی"},
	"ve": {Code: "ve", Name: "Venda", NativeName: "Tshivenḓa", PersianName: "وندا"},
	"vi": {Code: "vi", Name: "Vietnamese", NativeName: "Tiếng Việt", PersianName: "ویتنامی"},
	"vo": {Code: "vo", Name: "Volapük", NativeName: "Volapük", PersianName: "ولاپوک"},
	"wa": {Code: "wa", Name: "Walloon", NativeName: "Walon", PersianName: "والون"},
	"wo": {Code: "wo", Name: "Wolof", NativeName: "Wollof", PersianName: "ولوف"},
	"xh": {Code: "xh", Name: "Xhosa", NativeName: "IsiXhosa", PersianName: "خوسا"},
	"yi": {Code: "yi", Name: "Yiddish", NativeName: "ייִדיש", PersianName: "یدیش"},
	"yo": {Code: "yo", Name: "Yoruba", NativeName: "Yorùbá", PersianName: "یوروبا"},
	"za": {Code: "za", Name: "Zhuang", NativeName: "Saɯ cueŋƅ", PersianName: "ژوانگ"},
	"zh": {Code: "zh", Name: "Chinese", NativeName: "中文", PersianName: "چینی"},
	"zu": {Code: "zu", Name: "Zulu", NativeName: "IsiZulu", PersianName: "زولو"},
}

// get language by code
func GetLanguageByCode(code string) (Language, error) {
	if lang, ok := Languages[code]; ok {
		return lang, nil
	}
	return Language{}, ErrorLanguageNotFound
}
